CREATE TABLE CREDIT_FOR_ORDER (
    USER_ID   VARCHAR(255) NOT NULL,
    ORDER_ID  VARCHAR(255) NOT NULL UNIQUE,
    AMOUNT    DOUBLE       NOT NULL,
    STATUS    VARCHAR(50)  NOT NULL,
    LIFETIME  DATETIME     NOT NULL
);

CREATE INDEX idx_credits
    ON CREDIT_FOR_ORDER(USER_ID);